### ISSUE TITLE
Some suggestions 

### ISSUE THREAD

**Issue by DrPingas8** [zaeonNineZero/NineZero-Gun-Expansion#13]
Magnum - A revolver that uses medium bullets and does more damage but has more recoil.

Heavy Magnum/Revolver - A revolver that uses advanced bullets with an ammo capacity of 5 and does a lot of damage but has a ton of recoil

Anti-material Rifle - A rifle that uses a new ammo type and does monumentally more damage than any other gun

Derringer - A small 2 round pistol that would be the cheapest gun to craft 

These are just some suggestions, No pressure

**Comment by zaeonNineZero** [comment]
The Magnum seems a bit too redundant right now with the Revolver (and potentially the Heavy Pistol) fulfilling the niche of a higher-power, slower-firing handgun.

I will consider the idea of the Heavy Revolver. It has a viable niche since it would be the only handgun in NZGE and CGM to use advanced bullets. (The Heavy Pistol would use medium bullets)

I like the Anti-Material Rifle concept and will add that as an in-consideration item. If it does get added, it'll almost certainly be based on the PGM Hecate II.

The Derringer is an interesting idea, but given that guns have no durability and the pistol only costs 15 iron, most players will likely save up for the pistol instead. I'll keep it in mind but it's unlikely to be added right now.

Thank you for your suggestions!
