### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by tankyap** [zaeonNineZero/NineZero-Gun-Expansion#16]
- Straight to the point pls add some sort of custom sensitivity / multiplier for the Ballistic scope, I am struggled to aim because of how low the sens is, and yes, the sensitivity options exist but still it will affect my hip fire too. (And also make the scope frame less chunky, its obstructing the view while ADSing, at least probably make the frame smaller or clear sight to be bigger.)
- Add a new silenced barrel which has that signature rectangular look, primally the model will be from Silencerco Osprey / 22Sparrow Rectangular suppressors. About the stat, well you can do all your own, probably a silenced trait, a few accuracy and range boosts, couple of ADS loss will do the job.
- Add a new semi auto rifle (SKS) that has good dmg (15), a bit slow fire rate because of the trigger finger enchantment and a bit moderate recoil and mag size (advaced bullet).
- If you think the original CGM rocket launcher isn't enough, well you need to add the overkill Four Barreled Rocket Launcher based on "M202 Flash" with heavy dmg output but slow reload time.

If you can't do all of that is totally fine, I'm not forcing it.

**Comment by zaeonNineZero** [comment]
1. I don't think there is much I can do with the scope sensitivity since it's linked to the scope's FOV modifier. There's no parameter to directly control the sensitivity multiplier of individual attachments. I can see what I can do about the ADS model parameters though to reduce obstructions in the ADS view.
2. I will consider it. I would probably add a cylindrical suppressor model as well as a counterpart to it. Stat-wise they will have to be balanced around the CGM suppressor, but I'll make sure they have usable stats regardless.
3. This might be too redundant since the Infantry Rifle exists, but I'll list it as in consideration anyway. I still haven't decided on what to do with all the redundant guns on the roadmap, so if this SKS-based rifle gets added it might wind up in a companion addon instead of in NZGE.
4. I think this is unnecessary, since you can accomplish the same with the Over Capacity enchantment on a Bazooka. But like above, if the redundant guns get their own addon then maybe it'll find a home there.

Thank you for the suggestions.

**Comment by zaeonNineZero** [comment]
Since 1. and 2. are addressed and .3 and .4 would go in Redundant Guns rather than NZGE, I will be closing this issue. Thank you for the feedback!
