### ISSUE TITLE
Uncompatibility with Mr Pineapple's Toy Guns

### ISSUE THREAD

**Issue by amiga992** [zaeonNineZero/NineZero-Gun-Expansion#21]
Hello,

I play on 1.16.5 and I have both NineZero's Gun Expansion and Mr Pineapple's Toy Guns installed. There is a toy gun called revolver which incorrectly uses basic bullets instead of rubber darts.
I believe this is because this mod features a revolver, and their IDs are the exact same. I feel like this is more a problem on the toy gun mod, but I see more activity here.

Is this as easy fix or just I assume it is? (I'm not really familiar with how java coding works, so it could be a whole different issue)

Sorry if this isn't relevant.

Thanks :)

**Comment by zaeonNineZero** [comment]
[This is a known bug](https://github.com/MrCrayfish/MrCrayfishGunMod/issues/392) with CGM versions below 1.3.0 where the gun data handler does not consider mod ID namespaces. The update that fixed this bug was never released on 1.16.5 as support for that version was discontinued.

Unfortunately, there's nothing I can do on my end in this case without breaking compatibility with previous versions of NZGE for 1.16.5.
