### ISSUE TITLE
[Request] can you add more pistols?

### ISSUE THREAD

**Issue by trashcan585868** [zaeonNineZero/NineZero-Gun-Expansion#30]
i would like to see more pistols,  for example: a beretta shaped compact pistol

**Comment by zaeonNineZero** [comment]
Generally speaking, most new guns I make will be added in my next CGM addon, Redundant Guns (itself an addon to NZGE). A Beretta 9mm pistol (as the 'Combat Pistol') is included among the guns that will be part of the first release. NZGE may receive another new gun or two if they fill a vacant niche or otherwise differentiate themselves enough from others (i.e. a lever-action rifle), but otherwise I plan to shift new guns to Redundant Guns if they overlap too much with an existing gun in NZGE.

I have a snapshot build of Redundant Guns uploaded in the mod's GitHub repo. Feel free to download it and give it a try, if for no other reason than to check out the Beretta-inspired Combat Pistol.

**Comment by trashcan585868** [comment]
when is 1.5.0's set release date?

**Comment by trashcan585868** [comment]
i heard from the roadmap that there would be a 1.5.0 major release
